version: "3"

volumes:
  alcarin_api_data:

services:
  webpage:
    build: ./alcarin_webpage
    working_dir: /code
    command: mix phx.server
    volumes:
      - ./alcarin_webpage:/code
    ports:
      - "80:4000"

  api:
    build: ./alcarin_api
    working_dir: /code
    command: mix phx.server
    volumes:
      - ./alcarin_api:/code
    ports:
      - "4000:4000"
    links:
      - postgres:postgres.link

  postgres:
    image: postgres:9.6
    volumes:
      - alcarin_api_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alcarin
      POSTGRES_PASSWORD: alcarin
      POSTGRES_DB: alcarin
    ports:
      - "5432:5432"
